### PR TITLE
Add ProhibitUnusedPrivateConstructorCheck

### PR DESCRIPTION
**Pull request by vladislav-yevtushenko**
Fix #[1258](https://github.com/yegor256/qulice/issues/1258): Implement check for private constructor usage

- Added a check to ensure private constructors are used at least once.
- Included test cases validation.

@yegor256 kindly review.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@vladislav-yevtushenko thanks for your contribution! There is a problem with XML. Try to run xcop locally and see the output.

**Comment by vladislav-yevtushenko** [comment]
@yegor256 I have fixed xcop validation error. Please review it. Thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@vladislav-yevtushenko thanks a lot!

**Pull request merged**
