### PR TITLE
[#1198] update pmd to the latest

### PR DESCRIPTION
**Pull request by pnatashap**
- update pms to the latest
- update checkstyle for the latest
- update some dependencies
- remove duplicated rules (they are part of pmd)
- update some rules
- update used qulice to 0.22

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look. this version does not produce NPE
New rules that start failing (can be disabled):
JUnitAssertionsShouldIncludeMessage - https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html#junitassertionsshouldincludemessage
UseShortArrayInitializer - https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#useshortarrayinitializer
CloseResource - https://pmd.github.io/pmd/pmd_rules_java_errorprone.html#closeresource
DoubleBraceInitialization - https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html#doublebraceinitialization
StringInstantiation - https://pmd.github.io/pmd/pmd_rules_java_performance.html#stringinstantiation
ArrayIsStoredDirectly - https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html#arrayisstoreddirectly 
ParameterAssignmentCheck (failed now on some existing lambdas) - https://checkstyle.sourceforge.io/checks/coding/parameterassignment.html

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
