### PR TITLE
[#1242] fix diamond operator false positive warning

### LINKED ISSUE #1242: diamond operator check gives false positive
This is the code:

```
import java.util.Map;
import org.cactoos.map.MapEntry;
import org.cactoos.map.MapOf;

void foo() {
  Map<String, String> params = new MapOf<String, String>(
    new MapEntry<>("a", "foo"),
    new MapEntry<>("b", "foo")
  );
}
```

Qulice complains with `PMD.UseDiamondOperator` and `DiamondOperatorCheck`. However, I can't turn `MapOf<String, String>` into `MapOf<>`, because it won't compile. Can we do something about this?

### PR DESCRIPTION
**Pull request by pnatashap**
- disable PMD.UseDiamondOperator
- one more exception for DiamondOperatorCheck

Fix #1242

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor status

**Comment by yegor256** [comment]
@pnatashap thanks!

**Pull request merged**
