### PR TITLE
#1055: RegexpSinglelineCheck applies to *.png, *.js, *.css files

### PR DESCRIPTION
**Pull request by dgroup**
#1055 
https://checkstyle.sourceforge.io/config_regexp.html#RegexpSingleline

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this pull request

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @krzyk[/z](https://www.0crat.com/u/krzyk) please review this and merge or reject

**Comment by krzyk** [comment]
@dgroup we want this to apply also to other file types, not only java, so I'm not sure how to do it, a black list or a white list of extensions. Or maybe some clever binary file recognition.

**Comment by dgroup** [comment]
@krzyk , can you define the list of the supported files? 
The `fileExtensions` supports multiple extensions thus we can list them.
This doesn't look complex.

**Comment by dgroup** [comment]
@krzyk , @yegor256 , @davvd ,
can you define the list of the supported files for this rule?
The `fileExtensions` supports multiple extensions thus we can list them.

**Comment by dgroup** [comment]
@krzyk , up

**Comment by dgroup** [comment]
@krzyk up

**Comment by dgroup** [comment]
@krzyk up

**Comment by dgroup** [comment]
@krzyk up

**Comment by dgroup** [comment]
@krzyk up

**Comment by dgroup** [comment]
@krzyk @yegor256 , up.
Could you please have a look into this issue.
The PR is available.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
