### PR TITLE
reports-check.yml

### PR DESCRIPTION
**Pull request by h1alexbel**
This action will validate quality of incoming bug reports (github issues here) and post the possible improvements to the author of that report. Example of work: 

image

More information you can find in our [README](https://github.com/tracehubpm/reports-check-action)

### CODE REVIEW

**Comment by h1alexbel** [comment]
@yegor256, @pnatashap what do you think?

**Comment by yegor256** [comment]
@h1alexbel let's try it. do I need to set the OPENAI token?

**Comment by h1alexbel** [comment]
@yegor256 yes, you can use either `openai_token` or `deepinfra_token`

**Comment by yegor256** [comment]
@h1alexbel I defined `OPENAI_TOKEN`

**Pull request merged**
