### PR TITLE
Visit package definitions in MultilineJavadocTagsCheck

### LINKED ISSUE #1072: MultilineJavadocTagsCheck in package-info.java
MultilineJavadocTagsCheck is forcing to have a one-space indentation for javadoc tags that span into multiple lines (for example @todo puzzles tags). However, this check is not done for package-info.java files. Sometimes it is useful to make a puzzle concerning a whole package and the most suitable place to put it is the `package-info.java` file. It would be nice to make this check especially that pdd gem is doing this check and makes rultor merge scripts to fail.

### PR DESCRIPTION
**Pull request by MikailBag**
Should fix #1072

### CODE REVIEW

**Comment by pnatashap** [comment]
@MikailBag it is good to have tests for the change to understand the reason for the change

**Review by pnatashap — CHANGES_REQUESTED** [review]
Valid formatting this comment also should be added to test to make sure that we do not raise error on it

**Comment by MikailBag** [comment]
Thank you for comment, I've added a doc-comment to Valid.java.

**Review by pnatashap — APPROVED** [review]
looks good

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
