### PR TITLE
Fix issue 793

### PR DESCRIPTION
**Pull request by Scott-Huang**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

I went through the above checklist and I can say "yes" to each point. This code change includes a test case and an additional rule (Return empty collection rather than null) for fixing issue 793.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor ping

**Comment by yegor256** [comment]
@Scott-Huang it seems that your XML formatting is not canonical. [xcop](https://github.com/yegor256/xcop) doesn't like it.

**Comment by Scott-Huang** [comment]
@yegor256 Sorry, I haven't uploaded the file to be tested. I think that was the cause of the build error.

**Comment by yegor256** [comment]
@Scott-Huang could be, but you also have to fix the formatting of the `ruleset.xml`. Try to run `xcop` locally and you will see what it complains about.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Scott-Huang one problem is still there :) please, fix

**Comment by yegor256** [comment]
@rultor merge

**Comment by Scott-Huang** [comment]
I don't quite understand the problem here. I can cancel the pull request if the problem is not trivial.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Scott-Huang it's CI/CD problem, no worries, will fix it now

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Scott-Huang thanks!

**Pull request merged**
