### PR TITLE
For #1004: Enforce since tag in inner classes

### PR DESCRIPTION
**Pull request by paulodamaso**
For #1004: Enforce since tag in inner classes
- Corrected `JavadocTagsCheck.java`
- Added check execution to tests and validation
- Corrected sample classes for other tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1013](https://github.com/teamed/qulice/issues/1013) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1013](https://github.com/teamed/qulice/issues/1013) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/ebd287ee-c4a4-4e85-9dbf-a8e1b6bbe66a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @krzyk[/z](https://www.0crat.com/u/krzyk) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@krzyk PLease take a look, 0crat assigned me my own pull request

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by krzyk** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1013](https://github.com/teamed/qulice/issues/1013) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/teamed/qulice/issues/1013#issuecomment-458935449))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
